// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebPACS.DataContext;

namespace WebPACS.Migrations
{
    [DbContext(typeof(Databasecontext))]
    [Migration("20200817122152_addInitial")]
    partial class addInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebPACS.Areas.Administrator.Models.AdministratorModel", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdminEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminID");

                    b.ToTable("administratorModel");
                });

            modelBuilder.Entity("WebPACS.Areas.Customer.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AADHARNo")
                        .HasColumnType("bigint");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("AlternativeContactNumber")
                        .HasColumnType("bigint");

                    b.Property<long?>("AnnualIncome")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ApplicationDateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ApplicationDateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerCaste")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CustomerMobileNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomerSubCaste")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DaughterAge")
                        .HasColumnType("datetime2");

                    b.Property<string>("DaughterFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DaughterLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DaughterMiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrivingLicense")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FatherAge")
                        .HasColumnType("datetime2");

                    b.Property<string>("FatherFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherMiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GaurdianAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GaurdianContactNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GaurdianDateofBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("GaurdianDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GaurdianFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GaurdianFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GaurdianGender")
                        .HasColumnType("datetime2");

                    b.Property<string>("GaurdianLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GaurdianMiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GaurdianPincode")
                        .HasColumnType("int");

                    b.Property<string>("GaurdianTaluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GaurdianVillage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Housenumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MapsLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MotherAge")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotherFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherMiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomineeAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NomineeContactNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NomineeDOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomineeDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomineeFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NomineePincode")
                        .HasColumnType("int");

                    b.Property<string>("NomineeTaluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomineeVillage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Pincode")
                        .HasColumnType("int");

                    b.Property<string>("RationCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelationwithCustomer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SonAge")
                        .HasColumnType("datetime2");

                    b.Property<string>("SonFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SonLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SonMiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SpouseAge")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpouseFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpouseGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpouseLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpouseMiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Taluk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Village_City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_Daughter")
                        .HasColumnType("bit");

                    b.Property<bool>("is_Father")
                        .HasColumnType("bit");

                    b.Property<bool>("is_Gaurdian")
                        .HasColumnType("bit");

                    b.Property<bool>("is_Mother")
                        .HasColumnType("bit");

                    b.Property<bool>("is_Son")
                        .HasColumnType("bit");

                    b.Property<bool>("is_Spouse")
                        .HasColumnType("bit");

                    b.Property<bool>("is_minor")
                        .HasColumnType("bit");

                    b.Property<string>("street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("customerModel");
                });

            modelBuilder.Entity("WebPACS.Areas.DCCB.Models.DCCB", b =>
                {
                    b.Property<int>("DccbID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("DccbID");

                    b.ToTable("DCCBmodel");
                });

            modelBuilder.Entity("WebPACS.Areas.Deposit.Models.Deposit", b =>
                {
                    b.Property<int>("DepositID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("DepositID");

                    b.ToTable("DepositModel");
                });

            modelBuilder.Entity("WebPACS.Areas.FinYear_ROI.Models.FinYear_ROI", b =>
                {
                    b.Property<int>("FinYear_ROI_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("FinYear_ROI_ID");

                    b.ToTable("FinYear_ROImodel");
                });

            modelBuilder.Entity("WebPACS.Areas.SCB.Models.SCB", b =>
                {
                    b.Property<int>("SCB_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("SCB_ID");

                    b.ToTable("SCBmodel");
                });
#pragma warning restore 612, 618
        }
    }
}
